name = "wineshop-cdn"
main = "workers/cdn.ts"
compatibility_date = "2024-01-01"

[vars]
# Add your environment variables here

[[kv_namespaces]]
binding = "CDN_CACHE"
id = "your-kv-namespace-id"

[triggers]
crons = []

[site]
bucket = "./public" 